/* LDS-02 LiDAR serial parser.
   Packet format: 47 bytes, sync byte 0x54, type 0x2C,
   start/end angle in centidegrees, 12 distance samples between them */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <errno.h>
#include <time.h>

#include "ipc_common.h"
#include "config.h"
#include "lidar_driver.h"

/* Calibration offset generated by RTS_calibrate.py.
   Rotates raw sensor angles so 0 deg = robot physical forward
   regardless of how the turret was oriented at power-on */
#if __has_include("calibration.h")
    #include "calibration.h"
#else
    #define LIDAR_FORWARD_OFFSET_DEG 0
    #warning "calibration.h missing - run RTS_calibrate.py"
#endif

#define LDS02_SYNC      0x54
#define PKT_TYPE_BYTE   0x2C
#define PKT_LEN         47
#define PKT_SAMPLES     12

#define OFF_TYPE        1
#define OFF_START_ANG   4
#define OFF_SAMPLES     6
#define OFF_END_ANG     42
#define OFF_CHECKSUM    46

#define SAMPLE_STRIDE   3
#define SAMPLE_DIST     0
#define SAMPLE_QUAL     2

/* CLOCK_MONOTONIC never jumps backward (unlike REALTIME with NTP),
   safe for timestamps and interval math */
static uint64_t now_us(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec  * 1000000ULL
         + (uint64_t)ts.tv_nsec / 1000ULL;
}

/* termios wants symbolic constants, not integers */
static speed_t baud_to_speed(int baud)
{
    switch (baud) {
        case 9600:   return B9600;
        case 19200:  return B19200;
        case 38400:  return B38400;
        case 57600:  return B57600;
        case 115200: return B115200;
        case 230400: return B230400;
        default:
            fprintf(stderr, "lidar_driver: unsupported baud %d\n", baud);
            return B0;
    }
}

/* Little-endian 16-bit read. Byte-by-byte instead of pointer cast
   to avoid misaligned access (undefined behavior in C) */
static uint16_t read_le_u16(const uint8_t *buf, int offset)
{
    return (uint16_t) buf[offset]
         | ((uint16_t)buf[offset + 1] << 8);
}

/* Extract 12 samples from one validated packet into the scan array.
   Called with scan_mutex held */
static int parse_packet(const uint8_t *pkt, scan_t *scan, uint32_t *seq)
{
    if (pkt[OFF_TYPE] != PKT_TYPE_BYTE) return 0;

    /* Checksum skipped - LDS-02 algorithm differs from documented,
       sync + type check proved sufficient in practice */

    /* Angles stored as centidegrees (18000 = 180.00 deg) */
    float start_deg = read_le_u16(pkt, OFF_START_ANG) / 100.0f;
    float end_deg   = read_le_u16(pkt, OFF_END_ANG)   / 100.0f;

    for (int i = 0; i < PKT_SAMPLES; i++) {

        int offset = OFF_SAMPLES + i * SAMPLE_STRIDE;

        uint16_t dist_mm = read_le_u16(pkt, offset + SAMPLE_DIST);
        uint8_t  quality = pkt[offset + SAMPLE_QUAL];

        /* Reject: no return, inside sensor dead zone, beyond max,
           or weak signal */
        int valid = (dist_mm  >  0)
                 && (dist_mm  >= LIDAR_MIN_RANGE_MM)
                 && (dist_mm  <= LIDAR_MAX_RANGE_MM)
                 && (quality  >  0);

        /* Samples are evenly spaced across the packet arc -
           interpolate each one's angle */
        float raw_deg = start_deg
                      + (end_deg - start_deg) * (float)i / 12.0f;

        /* Rotate into robot frame. +360 before %360 because
           C modulo of a negative stays negative and we need
           a valid array index 0-359 */
        int robot_deg = ((int)roundf(raw_deg)
                        - LIDAR_FORWARD_OFFSET_DEG + 360) % 360;

        /* Invalid readings clear the slot so stale data from a
           previous rotation doesn't persist at this angle */
        scan->distance_mm[robot_deg] = valid ? (float)dist_mm : 0.0f;
        scan->valid[robot_deg]       = (uint8_t)valid;
    }

    scan->timestamp_us = now_us();
    scan->seq          = ++(*seq);

    return 1;
}

int lidar_driver_init(lidar_driver_t *drv, const char *port, int baud)
{
    memset(drv, 0, sizeof(*drv));
    drv->running = 1;

    /* O_NOCTTY: don't make this our controlling terminal.
       No O_NDELAY - that sets O_NONBLOCK which breaks blocking
       reads (learned this the hard way) */
    drv->fd = open(port, O_RDWR | O_NOCTTY);
    if (drv->fd < 0) {
        perror("lidar_driver_init: open()");
        return -1;
    }

    struct termios tty;
    if (tcgetattr(drv->fd, &tty) != 0) {
        perror("lidar_driver_init: tcgetattr()");
        close(drv->fd);
        return -1;
    }

    speed_t speed = baud_to_speed(baud);
    if (speed == B0) { close(drv->fd); return -1; }

    cfsetispeed(&tty, speed);
    cfsetospeed(&tty, speed);

    /* 8N1: 8 data bits, no parity, 1 stop bit */
    tty.c_cflag &= ~PARENB;
    tty.c_cflag &= ~CSTOPB;
    tty.c_cflag &= ~CSIZE;
    tty.c_cflag |=  CS8;
    tty.c_cflag &= ~CRTSCTS;
    tty.c_cflag |=  CREAD | CLOCAL;

    /* Raw mode: no line buffering, no echo, no signal chars */
    tty.c_lflag &= ~(ICANON | ECHO | ECHOE | ECHONL | ISIG);

    /* No flow control, no CR/NL translation - translation would
       silently corrupt any packet byte that happens to be 0x0D */
    tty.c_iflag &= ~(IXON | IXOFF | IXANY);
    tty.c_iflag &= ~(ICRNL | INLCR | IGNCR);
    tty.c_iflag &= ~IGNBRK;

    tty.c_oflag &= ~OPOST;
    tty.c_oflag &= ~ONLCR;

    /* VMIN=1 VTIME=0: read() blocks until at least 1 byte.
       Thread sleeps in the kernel instead of spinning - the
       kernel wakes it when the UART interrupt delivers data */
    tty.c_cc[VMIN]  = 1;
    tty.c_cc[VTIME] = 0;

    if (tcsetattr(drv->fd, TCSANOW, &tty) != 0) {
        perror("lidar_driver_init: tcsetattr()");
        close(drv->fd);
        return -1;
    }

    memset(&drv->scan, 0, sizeof(drv->scan));

    if (pthread_mutex_init(&drv->scan_mutex, NULL) != 0) {
        perror("lidar_driver_init: pthread_mutex_init()");
        close(drv->fd);
        return -1;
    }

    fprintf(stdout, "lidar_driver: opened %s at %d baud, "
                    "forward offset = %d deg\n",
            port, baud, LIDAR_FORWARD_OFFSET_DEG);
    return 0;
}

void *lidar_driver_task(void *arg)
{
    lidar_driver_t *drv = (lidar_driver_t *)arg;

    uint8_t  byte;
    uint8_t  pkt[PKT_LEN];
    uint32_t seq = 0;

    while (drv->running) {

        /* Sync hunting: discard bytes until 0x54. Self-recovers
           from any corruption or mid-stream connection */
        if (read(drv->fd, &byte, 1) != 1) {
            if (errno == EINTR) continue;
            perror("lidar_driver_task: read() sync byte");
            break;
        }
        if (byte != LDS02_SYNC) continue;

        /* read() may return fewer bytes than asked - kernel
           delivers whatever is buffered. Loop until full packet */
        pkt[0]       = LDS02_SYNC;
        int received = 1;

        while (received < PKT_LEN && drv->running) {
            int n = read(drv->fd,
                         pkt + received,
                         PKT_LEN - received);
            if (n < 0) {
                if (errno == EINTR) continue;
                perror("lidar_driver_task: read() packet body");
                drv->running = 0;
                break;
            }
            received += n;
        }

        if (received < PKT_LEN) break;

        /* Critical section: mutex prevents copy_scan from reading
           a half-updated scan (race condition). Hold time is
           microseconds - just the parse */
        pthread_mutex_lock(&drv->scan_mutex);
        parse_packet(pkt, &drv->scan, &seq);
        pthread_mutex_unlock(&drv->scan_mutex);
    }

    return NULL;
}

void lidar_driver_copy_scan(lidar_driver_t *drv, scan_t *out)
{
    /* Copy-under-lock: caller gets an immutable snapshot,
       driver keeps writing freely after unlock */
    pthread_mutex_lock(&drv->scan_mutex);
    memcpy(out, &drv->scan, sizeof(scan_t));
    pthread_mutex_unlock(&drv->scan_mutex);
}

void lidar_driver_destroy(lidar_driver_t *drv)
{
    close(drv->fd);
    pthread_mutex_destroy(&drv->scan_mutex);
    fprintf(stdout, "lidar_driver: closed.\n");
}
