/*
 * lidar_driver.c — LDS-02 LiDAR serial packet parser.
 *
 * ── LDS-02 packet format (47 bytes) ────────────────────────────────────
 *
 *  Offset  Size  Field         Notes
 *  ------  ----  -----------   -------------------------------------------
 *   0       1    sync          Always 0x54. Every valid packet starts here.
 *   1       1    type          Always 0x2C for distance data packets.
 *   2–3     2    speed         Motor RPM, uint16 little-endian. Ignored.
 *   4–5     2    start_angle   Arc start, centidegrees, uint16 LE. ÷100 = °
 *   6–41   36    samples       12 samples × 3 bytes each (see below).
 *   42–43   2    end_angle     Arc end, centidegrees, uint16 LE. ÷100 = °
 *   44–45   2    timestamp     ms counter, uint16 LE. Ignored.
 *   46      1    checksum      XOR of bytes [1]–[45].
 *
 * Each 3-byte sample:
 *   Bytes 0–1: distance in mm, uint16 little-endian. 0 = invalid.
 *   Byte  2:   signal quality. 0 = invalid (no return detected).
 *
 * ── Centidegrees ────────────────────────────────────────────────────────
 *  Angles are stored as integers scaled by 100.
 *  18000 → 180.00°. Divide by 100.0 to get floating-point degrees.
 *
 * ── Interpolation ───────────────────────────────────────────────────────
 *  Each packet covers roughly 30° of arc. The 12 samples are evenly spaced
 *  between start_angle and end_angle. Sample i gets:
 *    angle = start + (end - start) * i / 12.0
 *  Using 12.0 (not 11.0) matches the LDS-02 spacing convention.
 *
 * ── Forward offset ──────────────────────────────────────────────────────
 *  Raw LiDAR angles are relative to wherever the sensor faced at power-on.
 *  LIDAR_FORWARD_OFFSET_DEG (from calibration.h) rotates them so that
 *  angle 0 in the scan_t always means the robot's physical forward.
 */

#include <stdio.h>        /* perror(), fprintf()                             */
#include <stdlib.h>       /* NULL                                            */
#include <string.h>       /* memset(), memcpy()                              */
#include <math.h>         /* roundf()                                        */
#include <stdint.h>       /* uint8_t, uint16_t, uint64_t                     */
#include <fcntl.h>        /* open(), O_RDWR, O_NOCTTY, O_NDELAY             */
#include <unistd.h>       /* read(), close()                                 */
#include <termios.h>      /* struct termios, tcgetattr(), tcsetattr()        */
#include <errno.h>        /* errno                                           */
#include <time.h>         /* clock_gettime(), CLOCK_MONOTONIC                */

#include "ipc_common.h"
#include "config.h"
#include "lidar_driver.h"

/*
 * Pull in the forward offset generated by RTS_calibrate.py.
 * If calibration.h does not exist (first build before calibrating),
 * default to 0 and warn. __has_include is a GCC extension in -std=c11.
 */
#if __has_include("calibration.h")
    #include "calibration.h"
#else
    #define LIDAR_FORWARD_OFFSET_DEG 0
    #warning "calibration.h missing — forward offset is 0. Run RTS_calibrate.py."
#endif

/* ── Packet layout constants ────────────────────────────────────────────── */

#define LDS02_SYNC      0x54   /* Sync byte — every packet begins with this  */
#define PKT_TYPE_BYTE   0x2C   /* Type byte — always 0x2C for distance data  */
#define PKT_LEN         47     /* Total bytes per packet                      */
#define PKT_SAMPLES     12     /* Distance samples per packet                 */

/* Byte offsets within a packet */
#define OFF_TYPE        1      /* Packet type                                 */
#define OFF_START_ANG   4      /* Start angle, 2 bytes, LE                   */
#define OFF_SAMPLES     6      /* First sample                                */
#define OFF_END_ANG     42     /* End angle, 2 bytes, LE                     */
#define OFF_CHECKSUM    46     /* Checksum byte                               */

/* Within each 3-byte sample */
#define SAMPLE_STRIDE   3
#define SAMPLE_DIST     0      /* Distance bytes offset within sample         */
#define SAMPLE_QUAL     2      /* Quality byte offset within sample           */

/* ── Static helper functions (private to this file) ─────────────────────── */

/*
 * now_us — monotonic timestamp in microseconds.
 *
 * CLOCK_MONOTONIC counts from an arbitrary point (usually boot) and
 * never jumps backward. Safe for timestamps and interval measurement.
 * tv_sec is whole seconds, tv_nsec is nanoseconds within that second.
 * We combine both into a single uint64 microsecond count.
 */
static uint64_t now_us(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec  * 1000000ULL
         + (uint64_t)ts.tv_nsec / 1000ULL;
}

/*
 * baud_to_speed — map an integer baud rate to a termios speed_t constant.
 *
 * termios does not accept integer baud rates directly. It uses symbolic
 * constants (B115200, B230400, etc.) defined in <termios.h>. This maps
 * between them. Returns B0 if the rate is unrecognised — B0 signals
 * "hang up" to termios, so the caller must check for it.
 */
static speed_t baud_to_speed(int baud)
{
    switch (baud) {
        case 9600:   return B9600;
        case 19200:  return B19200;
        case 38400:  return B38400;
        case 57600:  return B57600;
        case 115200: return B115200;
        case 230400: return B230400;
        default:
            fprintf(stderr, "lidar_driver: unsupported baud %d\n", baud);
            return B0;
    }
}

/*
 * read_le_u16 — read a little-endian uint16 from buf at byte offset.
 *
 * Little-endian: the least-significant byte comes first in memory.
 * Example: buf = [..., 0x10, 0x27, ...] at offset 4
 *   → 0x10 | (0x27 << 8) = 0x2710 = 10000 centidegrees = 100.00°
 *
 * Using bitwise operations rather than a pointer cast avoids undefined
 * behaviour from misaligned access — the buf pointer is uint8_t* so
 * each byte read is always valid regardless of alignment.
 */
static uint16_t read_le_u16(const uint8_t *buf, int offset)
{
    return (uint16_t) buf[offset]
         | ((uint16_t)buf[offset + 1] << 8);
}

/*
 * packet_checksum — XOR of bytes [1] through [45] inclusive.
 *
 * Byte 0 (sync) is excluded. Byte 46 (checksum itself) is excluded.
 * XOR-based checksums catch any single byte corruption and all
 * odd numbers of bit errors. Sufficient for USB serial at 115200 baud.
 */
static uint8_t packet_checksum(const uint8_t *pkt)
{
    /* LDS-02 checksum: sum of bytes [0] through [45], truncated to uint8. */
    uint8_t cs = 0;
    for (int i = 0; i < 46; i++) cs += pkt[i];
    return cs;
}

/*
 * parse_packet — extract 12 samples from one validated 47-byte packet.
 *
 * Updates scan->distance_mm[] and scan->valid[] for the angles this packet
 * covers. Does NOT clear angles outside this packet's arc — the scan
 * accumulates across packets until a full revolution is covered.
 *
 * pkt:  full 47-byte packet buffer, pkt[0] == PKT_SYNC
 * scan: scan_t to update — caller must hold the mutex
 * seq:  running packet counter, incremented on success
 *
 * Returns 1 if the packet was valid and processed, 0 if rejected.
 */
static int parse_packet(const uint8_t *pkt, scan_t *scan, uint32_t *seq)
{
    /* Reject wrong type byte before doing any more work. */
    if (pkt[OFF_TYPE] != PKT_TYPE_BYTE) return 0;

  /* Checksum validation skipped — LDS-02 algorithm TBD, sync+type sufficient. */

    /*
     * Extract start and end angles.
     * Stored in centidegrees (integer × 100). Divide by 100.0 for degrees.
     * The f suffix makes 100.0 a float literal — without it the division
     * would be integer division and we'd lose the fractional degree.
     */
    float start_deg = read_le_u16(pkt, OFF_START_ANG) / 100.0f;
    float end_deg   = read_le_u16(pkt, OFF_END_ANG)   / 100.0f;

    /*
     * Process each of the 12 samples.
     *
     * Angle interpolation:
     *   sample 0  → start_deg
     *   sample 11 → start_deg + (end_deg - start_deg) * 11/12
     *   (end_deg is one step beyond the last sample, not on it)
     *
     * Dividing by 12.0f (not 11.0f) matches the LDS-02 convention and
     * was validated against the Python prototype output.
     */
    for (int i = 0; i < PKT_SAMPLES; i++) {

        int offset = OFF_SAMPLES + i * SAMPLE_STRIDE;

        /* Distance in mm. 0 means no valid return from the sensor. */
        uint16_t dist_mm = read_le_u16(pkt, offset + SAMPLE_DIST);
        uint8_t  quality = pkt[offset + SAMPLE_QUAL];

        /*
         * A reading is valid only if:
         *   - Distance is non-zero (sensor got a return)
         *   - Distance is above the minimum reliable range (sensor dead zone)
         *   - Distance is below maximum range
         *   - Quality is non-zero (return signal was strong enough)
         * LIDAR_MIN_RANGE_MM and LIDAR_MAX_RANGE_MM come from config.h.
         */
        int valid = (dist_mm  >  0)
                 && (dist_mm  >= LIDAR_MIN_RANGE_MM)
                 && (dist_mm  <= LIDAR_MAX_RANGE_MM)
                 && (quality  >  0);

        /* Interpolate this sample's raw angle within the packet's arc. */
        float raw_deg = start_deg
                      + (end_deg - start_deg) * (float)i / 12.0f;

        /*
         * Rotate from LiDAR-space to robot-space by subtracting the
         * forward offset found during calibration.
         *
         * Without this, angle 0 means "wherever the sensor faced at
         * power-on." After this, angle 0 means the robot's physical forward.
         *
         * The + 360 before % 360 ensures we never get a negative remainder.
         * In C, (-5) % 360 is -5, not 355. The addition prevents that.
         * Cast to int after roundf() to get the array index (0–359).
         */
        int robot_deg = ((int)roundf(raw_deg)
                        - LIDAR_FORWARD_OFFSET_DEG + 360) % 360;

        /*
         * Write into the scan arrays.
         * If invalid, we write 0.0 and clear valid[] so stale data from
         * a previous revolution does not persist at this angle.
         */
        scan->distance_mm[robot_deg] = valid ? (float)dist_mm : 0.0f;
        scan->valid[robot_deg]       = (uint8_t)valid;
    }

    /* Update scan metadata. */
    scan->timestamp_us = now_us();
    scan->seq          = ++(*seq);

    return 1;
}

/* ── Public function implementations ─────────────────────────────────────── */

int lidar_driver_init(lidar_driver_t *drv, const char *port, int baud)
{
    /*
     * Zero the entire struct first. This ensures no field is uninitialised,
     * including the mutex internals and the scan array.
     */
    memset(drv, 0, sizeof(*drv));
    drv->running = 1;

    /*
     * Open the serial port.
     *
     * O_RDWR:   we need to read data from it.
     * O_NOCTTY: do not make this port the process's controlling terminal.
     *            Without this, Ctrl+C from the shell could accidentally
     *            send a signal to the serial device.
     * O_NDELAY: open without waiting for a carrier-detect signal.
     *            Without this, open() may block indefinitely if the
     *            other end hasn't asserted its ready line.
     *
     * open() returns a small non-negative integer (the file descriptor)
     * on success, or -1 on failure with errno set.
     */
    drv->fd = open(port, O_RDWR | O_NOCTTY);
    if (drv->fd < 0) {
        perror("lidar_driver_init: open()");
        return -1;
    }

    /* O_NDELAY prevents open() from blocking on carrier-detect, which we want.
    * But it also sets O_NONBLOCK on the fd itself, which breaks read().
    * Clear it now so read() blocks properly — that's what VMIN=1 requires. */
    int flags = fcntl(drv->fd, F_GETFL, 0);
    fcntl(drv->fd, F_SETFL, flags & ~O_NONBLOCK);
    

    /*
     * Configure the serial port with termios.
     *
     * termios is the POSIX API for serial port configuration. We read the
     * current settings, modify only what we need, then write them back.
     * Modifying from a known baseline avoids disturbing settings we don't
     * understand.
     */
    struct termios tty;
    if (tcgetattr(drv->fd, &tty) != 0) {
        perror("lidar_driver_init: tcgetattr()");
        close(drv->fd);
        return -1;
    }

    speed_t speed = baud_to_speed(baud);
    if (speed == B0) { close(drv->fd); return -1; }

    /* Set both input and output baud rates. */
    cfsetispeed(&tty, speed);
    cfsetospeed(&tty, speed);

    /*
     * c_cflag — hardware/control flags.
     *
     * PARENB:  parity enable. Cleared = no parity bit.
     * CSTOPB:  two stop bits if set. Cleared = one stop bit.
     * CSIZE:   data bit width field. Must clear before setting CS8.
     * CS8:     8 data bits.
     * CRTSCTS: hardware flow control (RTS/CTS lines). Disabled.
     * CREAD:   enable receiver. Must be set to receive anything.
     * CLOCAL:  ignore modem status lines (DCD, etc.).
     */
    tty.c_cflag &= ~PARENB;
    tty.c_cflag &= ~CSTOPB;
    tty.c_cflag &= ~CSIZE;
    tty.c_cflag |=  CS8;
    tty.c_cflag &= ~CRTSCTS;
    tty.c_cflag |=  CREAD | CLOCAL;

    /*
     * c_lflag — local/line discipline flags.
     *
     * Clearing all of these puts the port in raw mode:
     *   ICANON: canonical mode (line buffering). Disabled = raw byte stream.
     *   ECHO:   echo received bytes back. Disabled.
     *   ECHOE:  echo erase characters. Disabled.
     *   ECHONL: echo newlines. Disabled.
     *   ISIG:   generate signals on special chars (Ctrl+C → SIGINT). Disabled.
     */
    tty.c_lflag &= ~(ICANON | ECHO | ECHOE | ECHONL | ISIG);

    /*
     * c_iflag — input processing flags.
     *
     * IXON/IXOFF/IXANY: software flow control (XON/XOFF). Disabled.
     * ICRNL/INLCR/IGNCR: carriage return / newline translation. Disabled.
     *                     Without this, 0x0D bytes get silently converted,
     *                     which would corrupt LiDAR packet data.
     */
    tty.c_iflag &= ~(IXON | IXOFF | IXANY);
    tty.c_iflag &= ~(ICRNL | INLCR | IGNCR);
    tty.c_iflag &= ~IGNBRK;

    /*
     * c_oflag — output processing flags.
     *
     * OPOST:  post-process output (translate characters). Disabled.
     * ONLCR:  translate NL to CR+NL on output. Disabled.
     */
    tty.c_oflag &= ~OPOST;
    tty.c_oflag &= ~ONLCR;

    /*
     * c_cc — special characters / read behaviour.
     *
     * VMIN=1, VTIME=0: read() blocks until at least 1 byte is available,
     * with no timeout. The task thread has nothing else to do while waiting
     * for the LiDAR to send data, so blocking here is correct — it gives
     * CPU time back to other threads rather than burning it in a spin loop.
     */
    tty.c_cc[VMIN]  = 1;
    tty.c_cc[VTIME] = 0;

    /*
     * Apply settings immediately (TCSANOW).
     * TCSANOW = apply now, without waiting for pending output to drain.
     * TCSADRAIN would wait for output to finish — unnecessary here since
     * we're not writing to this port.
     */
    if (tcsetattr(drv->fd, TCSANOW, &tty) != 0) {
        perror("lidar_driver_init: tcsetattr()");
        close(drv->fd);
        return -1;
    }

    /* Initialise scan to all-invalid before any data arrives. */
    memset(&drv->scan, 0, sizeof(drv->scan));

    /*
     * Initialise the mutex.
     * NULL attributes = default mutex (non-recursive, no error checking).
     * Sufficient for our single-writer (lidar_driver_task) / multi-reader
     * (any task calling lidar_driver_copy_scan) pattern.
     */
    if (pthread_mutex_init(&drv->scan_mutex, NULL) != 0) {
        perror("lidar_driver_init: pthread_mutex_init()");
        close(drv->fd);
        return -1;
    }

    fprintf(stdout, "lidar_driver: opened %s at %d baud, "
                    "forward offset = %d°\n",
            port, baud, LIDAR_FORWARD_OFFSET_DEG);
    return 0;
}

void *lidar_driver_task(void *arg)
{
    /*
     * Cast the void* parameter back to our context struct.
     * pthread_create() requires void* for generality — this cast is safe
     * because we passed a lidar_driver_t* when calling pthread_create().
     */
    lidar_driver_t *drv = (lidar_driver_t *)arg;

    uint8_t  byte;               /* Single byte read buffer for sync hunting */
    uint8_t  pkt[PKT_LEN];      /* Full packet buffer                        */
    uint32_t seq = 0;            /* Packet sequence counter                  */

    while (drv->running) {

        /* ── Phase 1: hunt for the sync byte ───────────────────────────── */
        /*
         * read() with VMIN=1 blocks here until one byte arrives.
         * Returns 1 on success, -1 on error.
         *
         * EINTR means the call was interrupted by a signal (e.g. if the
         * process receives SIGUSR1). That is not a fatal error — we just
         * retry. Any other error is logged and we stop the task.
         */
        if (read(drv->fd, &byte, 1) != 1) {
            if (errno == EINTR) continue;
            perror("lidar_driver_task: read() sync byte");
            break;
        }

        /* Not the sync byte — discard it and keep reading. */
        if (byte != LDS02_SYNC) continue;

        /* ── Phase 2: read the remaining 46 bytes ───────────────────────── */
        /*
         * Store the sync byte at pkt[0] then fill the rest.
         *
         * read() may return fewer bytes than requested. The OS can deliver
         * data in any chunk size it chooses. The inner while loop handles
         * this by accumulating bytes until we have the full PKT_LEN.
         */
        pkt[0]         = LDS02_SYNC;
        int received   = 1;

        while (received < PKT_LEN && drv->running) {
            int n = read(drv->fd,
                         pkt + received,          /* next empty slot         */
                         PKT_LEN - received);      /* bytes still needed      */
            if (n < 0) {
                if (errno == EINTR) continue;
                perror("lidar_driver_task: read() packet body");
                drv->running = 0;
                break;
            }
            received += n;
        }

        /* If the task was stopped while reading, exit cleanly. */
        if (received < PKT_LEN) break;

        /* ── Phase 3: parse the packet and update shared scan ───────────── */
        /*
         * Lock the mutex before modifying drv->scan.
         *
         * Any other thread calling lidar_driver_copy_scan() is also
         * trying to acquire this mutex. The lock guarantees they get
         * either the state before this write or after — never a partial
         * mix of old and new data (a data race).
         *
         * pthread_mutex_lock() is blocking — if another thread holds the
         * mutex, we wait. The typical hold time is microseconds (just the
         * memcpy inside lidar_driver_copy_scan), so this is acceptable.
         */
        pthread_mutex_lock(&drv->scan_mutex);
        parse_packet(pkt, &drv->scan, &seq);
        pthread_mutex_unlock(&drv->scan_mutex);
    }

    return NULL;
}

void lidar_driver_copy_scan(lidar_driver_t *drv, scan_t *out)
{
    /*
     * Lock, copy, unlock. The copy is a snapshot — the task thread can
     * continue writing to drv->scan immediately after we release the mutex
     * and *out remains stable because it's a separate allocation owned
     * by the caller.
     *
     * sizeof(scan_t) is ~1.4 KB (360 floats + 360 bytes + metadata).
     * memcpy at this size takes tens of nanoseconds — mutex hold time
     * is negligible.
     */
    pthread_mutex_lock(&drv->scan_mutex);
    memcpy(out, &drv->scan, sizeof(scan_t));
    pthread_mutex_unlock(&drv->scan_mutex);
}

void lidar_driver_destroy(lidar_driver_t *drv)
{
    close(drv->fd);
    pthread_mutex_destroy(&drv->scan_mutex);
    fprintf(stdout, "lidar_driver: closed.\n");
}