#!/usr/bin/env python3
"""
calibrate.py

Run once after the sensor rig is assembled or repositioned.
Finds which LiDAR angle corresponds to physical forward on the chassis,
then writes that value into include/calibration.h.

Every other program reads calibration.h rather than hardcoding angles.
This is the same principle as config.h in the final C project — one file
that everyone depends on, one place to change when hardware changes.
"""

import serial, struct, time, os, re

LIDAR_PORT     = '/dev/ttyUSB0'
LIDAR_BAUD     = 115200
SAMPLE_SECONDS = 3
OUTPUT_PATH    = 'include/calibration.h'


def collect_scan(duration_s):
    """
    Open the LiDAR port and collect raw packets for duration_s seconds.
    Returns a dict mapping integer angle → list of distance readings (mm).
    Accumulating a list per angle lets us average out noise later.
    """
    ser     = serial.Serial(LIDAR_PORT, LIDAR_BAUD, timeout=2)
    samples = {}
    deadline = time.time() + duration_s

    while time.time() < deadline:
        # Hunt for sync byte — same logic as test_combined.py.
        if ser.read(1) != b'\x54':
            continue
        rest = ser.read(46)
        if len(rest) < 46 or rest[0] != 0x2C:
            continue
        pkt     = b'\x54' + rest
        start_a = struct.unpack_from('<H', pkt,  4)[0] / 100.0
        end_a   = struct.unpack_from('<H', pkt, 42)[0] / 100.0

        for i in range(12):
            dist = struct.unpack_from('<H', pkt, 6 + i * 3)[0]
            if dist > 0:
                angle = round(start_a + (end_a - start_a) * i / 12.0)
                # setdefault creates an empty list the first time we see an angle.
                samples.setdefault(angle, []).append(dist)

    ser.close()
    return samples


def find_forward_angle(samples):
    # Only consider angles with readings in the 200-400mm band.
    # Walls and furniture sit further away; this isolates the calibration target.
    averages = {
        a: sum(ds) / len(ds)
        for a, ds in samples.items()
        if 200 <= sum(ds) / len(ds) <= 400
    }
    if not averages:
        print("ERROR: No readings in 200-400mm range. Check hand position.")
        sys.exit(1)
    return min(averages, key=averages.get)

def write_calibration_header(forward_offset, path):
    """
    Write a C-style header file containing the calibration constants.

    Why a C header and not a plain text file?
    When we move to C code later, these same files get #included directly.
    The Python programs parse the #define lines with a regex.
    One file, one source of truth, two languages both read it.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, 'w') as f:
        f.write(
            "#ifndef CALIBRATION_H\n"
            "#define CALIBRATION_H\n"
            "\n"
            "/* Generated by calibrate.py — do not edit manually.       */\n"
            "/* Re-run calibrate.py if the sensor rig is reassembled.   */\n"
            "\n"
            "/* The LDS-02's 0-degree mark is wherever the sensor faces  */\n"
            "/* when it powers on — arbitrary. This offset is added to   */\n"
            "/* any angle lookup so that 'forward' always means forward. */\n"
           f"#define LIDAR_FORWARD_OFFSET_DEG  {forward_offset}\n"
            "\n"
            "/* Forward slice half-width: we treat OFFSET ± WINDOW as   */\n"
            "/* the 'front' zone when checking what's ahead.             */\n"
            "#define LIDAR_FORWARD_WINDOW_DEG  5\n"
            "\n"
            "#endif /* CALIBRATION_H */\n"
        )

    print(f"  Written: {path}")


# ── Main ──────────────────────────────────────────────────────────────────────

print("=== LiDAR Forward Calibration ===")
print("Hold your hand flat, 30 cm in front of the LiDAR.")
print("Keep all other objects beyond 40 cm during calibration.\n")

for i in range(3, 0, -1):
    print(f"  Starting in {i}...")
    time.sleep(1)

print(f"\nCollecting for {SAMPLE_SECONDS} seconds — hold still...")
samples = collect_scan(SAMPLE_SECONDS)

offset = find_forward_angle(samples)
print(f"  Forward angle: {offset}°")

write_calibration_header(offset, OUTPUT_PATH)
print("\nCalibration complete. Run RTS_test_IR_LiDAR.py now.")
