#ifndef CALIBRATION_H
#define CALIBRATION_H

/* Generated by calibrate.py — do not edit manually.       */
/* Re-run calibrate.py if the sensor rig is reassembled.   */

/* The LDS-02's 0-degree mark is wherever the sensor faces  */
/* when it powers on — arbitrary. This offset is added to   */
/* any angle lookup so that 'forward' always means forward. */
#define LIDAR_FORWARD_OFFSET_DEG  359

/* Forward slice half-width: we treat OFFSET ± WINDOW as   */
/* the 'front' zone when checking what's ahead.             */
#define LIDAR_FORWARD_WINDOW_DEG  5

#endif /* CALIBRATION_H */
